### ISSUE TITLE
Invisible avatar after DCL update since 20/10/2022

### ISSUE THREAD

**Issue by soq2000** [pmacom/dcldash#45]
Dear all,
We did use dcldash in our DCL project normally. Really thank you for such useful library.
However since 20/10/2022, in our since we see only 1 avatar, the one of ourself. To reproduce such circumstance, just include the lib dcldash in the package.json of any DCL sample project and you will see.
I capture a video to show you this issue.
[https://drive.google.com/file/d/19Fdn4RI3FCi0TCVVbOZ0MAkwX4fclPEu/view?usp=share_link](url)

**Comment by tyzoo** [comment]
I think theres a bug in 0.0.33 with Zones and should be fixed in 0.0.34, which has not been released yet, so you would need to run `npm install dcldash@next` to fix this
